namespace CriticalCompendiumInfrastructure.Enums
{
    public enum  MartialWeapon
    {
        All,
        Battleaxe,
        Flail,
        Glaive,
        Greataxe,
        Greatsword,
        Halberd,
        Lance,
        Longsword,
        Maul,
        Morningstar,
        Pike,
        Rapier,
        Scimitar,
        Shortsword,
        Trident,
        WarPick,
        Warhammer,
        Whip,
        Blowgun,
        CrossbowHand,
        CrossbowHeavy,
        Longbow,
        Net
    }
}
